version: '3.8'
services:
  db-postgres:
    image: postgres:14.2-alpine
    networks:
      - m_devops
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:6.7
    networks:
      - m_devops
    ports:
      - "80:80"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - PGADMIN_DEFAULT_EMAIL=mdevops@obs.org
      - PGADMIN_DEFAULT_PASSWORD=1234
      - PGADMIN_PORT=5000
    volumes:
      - ./volumes/pgadmin:/var/lib/pgadmin

networks:
  m_devops:
    driver: bridge
