version: '3.8'
services:
  db-postgres:
    image: postgres:14.1-alpine
    networks:
      - m_devops
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data

networks:
  m_devops:
    driver: bridge
